name: ubuntu

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - { cc: "gcc-8",      cxx: "g++-8"       }
        - { cc: "gcc-9",      cxx: "g++-9"       }
        - { cc: "gcc-10",     cxx: "g++-10"      }
        - { cc: "gcc-11",     cxx: "g++-11"      }
        # - { cc: "gcc-12",     cxx: "g++-12"      }
        # - { cc: "clang-5.0",  cxx: "clang++-5.0" }
        - { cc: "clang-6.0",  cxx: "clang++-6.0", repo_suffix: "" }
        - { cc: "clang-7",    cxx: "clang++-7", repo_suffix: ""   }
        - { cc: "clang-8",    cxx: "clang++-8", repo_suffix: ""   }
        - { cc: "clang-9",    cxx: "clang++-9", repo_suffix: "-9"   }
        - { cc: "clang-10",   cxx: "clang++-10", repo_suffix: "-10"  }
        - { cc: "clang-11",   cxx: "clang++-11", repo_suffix: "-11"  }
        - { cc: "clang-12",   cxx: "clang++-12", repo_suffix: "-12"  }
        - { cc: "clang-13",   cxx: "clang++-13", repo_suffix: "-13"  }
        - { cc: "clang-14",   cxx: "clang++-14", repo_suffix: "-14"  }
        - { cc: "clang-15",   cxx: "clang++-15", repo_suffix: "-15"  }
        - { cc: "clang-16",   cxx: "clang++-16", repo_suffix: "-16"  }
        - { cc: "clang-17",   cxx: "clang++-17", repo_suffix: ""  }

    name: "${{matrix.compiler.cc}}"
    steps:
    - uses: actions/checkout@v3

    - name: Configure clang
      run: |
        if [[ "${{matrix.compiler.cc}}" == "clang"* ]]; then
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal${{matrix.compiler.repo_suffix}} main"
          sudo apt update
          sudo apt install ${{matrix.compiler.cc}} -y
        fi

    - name: Configure gcc
      run: |
        if [[ "${{matrix.compiler.cc}}" == "gcc"* ]]; then
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install ${{matrix.compiler.cxx}} -y
        fi

    - name: Build Release
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        cmake --build . --config Release
        ctest --output-on-failure -C Release

    - name: Build Debug
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        cmake --build . --config Debug
        ctest --output-on-failure -C Debug
